In [0]:
import numpy as np
list1 = [1.0,2.0,3.0,4.0,5.0]
npy_array=np.array(list1, dtype=np.float64)
#convert list to array/matrix
npy_array.ndim
a=np.array([[1,2,3],[4,5,6],[7,8,9]], dtype=np.float64)
a.ndim #dimensions
a.shape #shape (3,3)
a.size #product of dimensions
a.itemsize #each var size in bytes
a.dtype.name
type(a)
np.indices((3,5))
np.eye(4) # same as identity matrix
np.identity(3) 
z = np.zeros((3,4), dtype=np.int) # prints 2d array with (x,y) dimensions and given dtype
z = np.ones((3,4), dtype=np.float64)
z = np.random.random(())
z = np.random.uniform(-3,5,(5,6)) # uniform distribution


#arrays and functions for plotting
x = np.linspace(-10,10,201) # returns numbers over an interval (start,stop,amt)
x1 = np.arange(-10.0,10.0,0.1) # returns values evenly over a given interval
sine = np.sin(x)

#matplot
import matplotlib.pyplot as plt
"""
#plt.plot(x,sine)
#plt.show() # primary view member function

quad1=x**2 + 2.0*x + 5.0
#plt.plot(x,quad1)
#plt.show()

quad1=x**2 + 2.0*x + 5.0
#plt.plot(x,quad1)
#plt.show()

def norm_func(x,mean,var):
  return 1.0/(var*(2*np.pi)**0.5)*np.exp(-1/2*((x-mean)/var)**2)

x=np.arange(-5,5.01,0.05)
pdf1=norm_func(x,0,0.2**0.5)
pdf2=norm_func(x,0,1.0**0.5)
pdf3=norm_func(x,0,5.0**0.5)
pdf4=norm_func(x,-2.0,0.5**0.5)


plt.plot(x,pdf1,color='blue',label="mean={} var^2={}".format(0,0.2))
plt.plot(x,pdf2,color='red',label="mean={} var^2={}".format(0,1.0))
plt.plot(x,pdf3,color='yellow',label="mean={} var^2={}".format(0,5.0))
plt.plot(x,pdf4,color='green',label="mean={} var^2={}".format(-2.0,0.5))
plt.legend()
plt.show()
"""


# 5.
x=np.linspace(-4,4,9)
y=np.linspace(-5,5,11)

xx,yy=np.meshgrid(x,y)
xx.shape
yy.shape

ellipse = xx**2 + 4*yy**4

#plt.contourf(xx,yy,ellipse,cmap='jet')

#plt.colorbar()
#plt.show()

random_data=np.random.random((11,9))
#plt.contour(xx,yy,random_data,cmap='jet')
#plt.colorbar()

xx1,yy1=np.meshgrid(x,y,indexing='ij')
#xx1 is transposed xx; yy1 is transposed yy
#np.all(xx==xx1.T)

np.all([1,2]==[1,3])


# 6.
xx,yy=np.meshgrid(x,y, sparse=True) # output designed to save memory
xx.shape
yy.shape

ell=xx**2 + yy**2

xm,ym=np.mgrid[-11:12:2.5,-11:12:2.5]  # each returned argument has the same shape

xm,ym=np.mgrid[-11:52:1j,-11:52:3j]    # third number sets the size (number of points to create)

#print(xm.shape)
#print(ym.shape)

xg,yg=np.ogrid[-11:12:3j,-11:12:3j]    # 5 total points including bounds
#print(xm)
xg,yg=np.broadcast_arrays(xm,yg)       # makes it so you can perform mathematical operations 
#print(yg)                              # on arrays with different shapes



# 7.
A=np.ones((5,3))
B=5*A
C=np.random.randint(-5,5,(3,5))
np.multiply(A,B)
A/B
A+=B
A**=B
np.sqrt(A)
np.power(A,2)
#np.exp(A)

np.dot(A,B.T)

a=np.array([[-2,1,1],[0,2,0],[-4,1,3]])
#print(a.shape)

b=np.array([4,5,6])
#print(b.T.shape)
c=np.dot(a,b.T)
#print(c.shape)

np.linalg.det(a)
np.linalg.inv(a)

print(a)
eigval, eigvec = np.linalg.eig(a)
print(eigval)
print(eigvec)


[[-2  1  1]
 [ 0  2  0]
 [-4  1  3]]
[-1.  2.  2.]
[[-0.70710678 -0.24253563  0.30151134]
 [ 0.          0.          0.90453403]
 [-0.70710678 -0.9701425   0.30151134]]
